[2018-07-25 13:35:45,252] PC-201608271350/ERROR/stderr: Traceback (most recent call last):
[2018-07-25 13:35:45,252] PC-201608271350/ERROR/stderr: File ".\run.py", line 89, in <module>
[2018-07-25 13:35:45,252] PC-201608271350/ERROR/stderr: 
[2018-07-25 13:35:45,252] PC-201608271350/ERROR/stderr: main()
[2018-07-25 13:35:45,252] PC-201608271350/ERROR/stderr: 
[2018-07-25 13:35:45,252] PC-201608271350/ERROR/stderr: File ".\run.py", line 70, in main
[2018-07-25 13:35:45,252] PC-201608271350/ERROR/stderr: 
[2018-07-25 13:35:45,252] PC-201608271350/ERROR/stderr: case_result, is_pass = test.run_case(index)
[2018-07-25 13:35:45,252] PC-201608271350/ERROR/stderr: 
[2018-07-25 13:35:45,252] PC-201608271350/ERROR/stderr: File "D:\python_code\APIAutoTest-master\api\runner.py", line 258, in run_case
[2018-07-25 13:35:45,252] PC-201608271350/ERROR/stderr: 
[2018-07-25 13:35:45,252] PC-201608271350/ERROR/stderr: is_login = Case.case[index].get('login')
[2018-07-25 13:35:45,252] PC-201608271350/ERROR/stderr: 
[2018-07-25 13:35:45,252] PC-201608271350/ERROR/stderr: KeyError
[2018-07-25 13:35:45,252] PC-201608271350/ERROR/stderr: :
[2018-07-25 13:35:45,252] PC-201608271350/ERROR/stderr: 0
[2018-07-25 13:35:45,252] PC-201608271350/ERROR/stderr: 
